### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by ixje** [MarkoPaul0/WireBait#21]
Like many others I'm new to lua and wireshark dissectors. I wish I had found this repo sooner, seems like a gem to me for helping me write the dissector more efficiently! Anyway, I'm trying to run [quickstart example one](https://github.com/MarkoPaul0/WireBait#example-1-dissecting-data-from-a-hexadecimal-string) but it errors (see below)

**Describe the bug**
![image](https://user-images.githubusercontent.com/6625537/82156367-0d507f00-987b-11ea-92a6-f77c4095c8cb.png)

**To Reproduce**
use commit: 2ca227cf8d969000d0aa029392facfb4d6ebe05c
try to run example code as shown in screenshot

**Expected behavior**
work as described in the readme 🙏 

PS: Example 2 using the pcap has a similar error
```

Program completed in 1.87 seconds (pid: 5189).
...ZeroBraneStudio/lualibs/wirebaitlib/primitives/Utils.lua:58: attempt to index global 'bit32' (a nil value)
stack traceback:
	...ZeroBraneStudio/lualibs/wirebaitlib/primitives/Utils.lua: in function 'getSrcIP'
	...aneStudio/lualibs/wirebaitlib/packet_info/PacketInfo.lua:72: in function 'new'
	...Studio/lualibs/wirebaitlib/dissector/DissectorRunner.lua:211: in function 'dissectPcap'
	...ualibs/wirebaitlib/dissector/example/demo_dissector2.lua:34: in main chunk
Debugging session completed (traced 0 instructions).
```

**Comment by MarkoPaul0** [comment]
I believe this issue should be easy to fix. In Zerobrane Studio, please go to
_**Project > Lua Interpreter**_ and select _**Lua 5.2**_. Then try to run the demo and it should work.

I wish this repo was the gem you are hoping it to be. Unfortunately, I haven't dedicated a lot of time to it and there are still tons of missing features that would make it feel like you are running your dissectors in Wireshark.

Anyways, let me know how it goes. Feel free to reach out if you need more help, or even better if you are interested in being a contributor haha.

Good luck!

**Comment by ixje** [comment]
Thanks for the quick response. Switching the interpreter indeed solved it 👍 
I'll play around with it more during the week and leave some feedback if I have ideas or issues
