### ISSUE TITLE
"=" doesn't work for pktInfo.cols.xxx

### ISSUE THREAD

**Issue by pffang** [MarkoPaul0/WireBait#8]
In WireShark, I can use method pktInfo.cols.xxx = "string" to set the display string for column, but in WireBait I can only use .set method.

**Comment by MarkoPaul0** [comment]
I can't remember if I implemented this either. I'm gonna look at it this weekend as well.
Thanks again for your feedback!

**Comment by MarkoPaul0** [comment]
@pffang could you provide an example of column for which it does not work? If you look at the [demo_dissector2.lua](examples/demo_dissector2.lua) you can see at line 69 that the feature you are talking about exists and seems to be working.

**Comment by pffang** [comment]
Sorry, I found this issue in 'dissectHexData'. It seems a limitation not a bug.
